name: Refactoring Report
on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
permissions:
  contents: read
  pages: write
  id-token: write
  pull-requests: write
  actions: read
concurrency:
  group: refactoring-pages-publish
  cancel-in-progress: false
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: Pogut/refactoringminer-action@fix/publishing-speed
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image: tsantalis/refactoringminer:latest