name: Refactoring Report
on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
permissions:
  contents: write
  pages: write
  pull-requests: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: Pogut/refactoringminer-action@main
        with:

          github-token: ${{ secrets.GITHUB_TOKEN }}
          # image: ghcr.io/pogut/refactoringminer:dev
          image: tsantalis/refactoringminer:latest

